# Generated by Django 6.0.6 on 2026-06-15 15:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=500)),
                ("tier", models.CharField(default="free", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="DeveloperAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=500)),
                ("tier", models.CharField(default="free", max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "billing_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("allowed_domains", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "developer_accounts",
            },
        ),
        migrations.CreateModel(
            name="SkillTaxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("canonical_name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "parent_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("synonyms", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "skill_taxonomy",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_name", models.CharField(default="Default Key", max_length=255)),
                ("secret_key", models.CharField(max_length=500, unique=True)),
                ("public_key", models.CharField(max_length=500, unique=True)),
                ("environment", models.CharField(default="production", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "api_keys",
            },
        ),
        migrations.CreateModel(
            name="BillingSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan", models.CharField(default="free", max_length=50)),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "developer",
                    models.ForeignKey(
                        db_column="developer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.developeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="DeveloperAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_name", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=500, unique=True)),
                ("public_key", models.CharField(max_length=500, unique=True)),
                ("environment", models.CharField(default="test", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "developer",
                    models.ForeignKey(
                        db_column="developer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.developeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "developer_api_keys",
            },
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("action_type", models.CharField(blank=True, max_length=50, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "metadata",
                    models.JSONField(blank=True, db_column="metadata", null=True),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        db_column="developer_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.developeraccount",
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        db_column="api_key_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.developerapikey",
                    ),
                ),
            ],
            options={
                "db_table": "api_usage_logs",
            },
        ),
        migrations.CreateModel(
            name="EmbedToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=500, unique=True)),
                ("allowed_domain", models.CharField(max_length=255)),
                ("permissions", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "developer",
                    models.ForeignKey(
                        db_column="developer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.developeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "embed_tokens",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("rounds", models.JSONField(default=list)),
                ("current_round_index", models.IntegerField(default=0)),
                ("status", models.CharField(default="active", max_length=50)),
                ("criteria", models.JSONField(default=dict)),
                ("inferred_skills", models.JSONField(default=list)),
                ("gmail_tokens", models.JSONField(blank=True, null=True)),
                ("gdrive_tokens", models.JSONField(blank=True, null=True)),
                (
                    "gdrive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gmail_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
            },
        ),
        migrations.CreateModel(
            name="IngestJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("total_files", models.IntegerField(default=0)),
                ("processed_files", models.IntegerField(default=0)),
                ("failed_files", models.IntegerField(default=0)),
                ("error_log", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "ingest_jobs",
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("referenced_candidate_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "chat_history",
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "resume_photo_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "resume_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("raw_resume_data", models.JSONField(default=dict)),
                ("normalized_skills", models.JSONField(default=list)),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("match_details", models.JSONField(default=dict)),
                (
                    "recommendation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_experience_years", models.FloatField(default=0.0)),
                ("current_round_index", models.IntegerField(default=0)),
                ("status", models.CharField(default="new", max_length=50)),
                ("source", models.CharField(default="upload", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                ("events", models.JSONField(default=list)),
                ("secret", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "developer",
                    models.ForeignKey(
                        db_column="developer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.developeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks",
            },
        ),
        migrations.CreateModel(
            name="WebhookDeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "webhook",
                    models.ForeignKey(
                        db_column="webhook_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.webhook",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_delivery_logs",
            },
        ),
        migrations.CreateModel(
            name="MonthlyUsageSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year_month", models.CharField(max_length=7)),
                ("parse_count", models.IntegerField(default=0)),
                ("match_count", models.IntegerField(default=0)),
                ("chat_count", models.IntegerField(default=0)),
                ("export_count", models.IntegerField(default=0)),
                ("total_api_calls", models.IntegerField(default=0)),
                (
                    "developer",
                    models.ForeignKey(
                        db_column="developer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.developeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "monthly_usage_summary",
                "unique_together": {("developer", "year_month")},
            },
        ),
    ]
