# Generated by Django 6.0.6 on 2026-06-16 14:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudScanLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("candidate_name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("originality_score", models.IntegerField(default=100)),
                ("ai_probability", models.IntegerField(default=0)),
                ("plagiarism_score", models.IntegerField(default=0)),
                ("status", models.CharField(default="Verified Clean", max_length=100)),
                ("portfolios", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "fraud_scan_logs",
            },
        ),
    ]
