# Generated by Django 6.0.6 on 2026-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_fraudscanlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyusagesummary",
            name="scan_count",
            field=models.IntegerField(default=0),
        ),
    ]
