# Generated by Django 6.0.6 on 2026-06-18 02:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_monthlyusagesummary_scan_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=500)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "resume_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("resume_data", models.JSONField(default=dict)),
                ("enhanced_resume", models.JSONField(default=dict)),
                ("skills", models.JSONField(default=list)),
                ("tier", models.CharField(default="free", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "job_seeker_accounts",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("application_received", "Application Received"),
                            ("status_updated", "Status Updated"),
                            ("new_match", "New Job Match"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_column="company_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.company",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        blank=True,
                        db_column="seeker_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.jobseekeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cover_note", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        db_column="candidate_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seeker_application",
                        to="api.candidate",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seeker_applications",
                        to="api.session",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        db_column="seeker_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="api.jobseekeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "job_applications",
                "unique_together": {("seeker", "session")},
            },
        ),
    ]
