# Generated by Django 6.0.6 on 2026-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_jobseekeraccount_notification_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="company_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="founded_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="hq_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="rating",
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name="company",
            name="website_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
