# Generated by Django 6.0.6 on 2026-06-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_company_about_company_company_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekeraccount",
            name="open_to",
            field=models.JSONField(default=dict),
        ),
    ]
