# Generated by Django 6.0.6 on 2026-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_jobseekeraccount_open_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="accepted_terms",
            field=models.BooleanField(default=False),
        ),
    ]
