# Generated by Django 6.0.6 on 2026-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_jobapplication_accepted_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="offer_letter_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
