# Generated by Django 6.0.6 on 2026-06-26 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_fraudscanlog_detailed_checks"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyBillingSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan", models.CharField(default="free", max_length=50)),
                ("payment_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_billing_subscriptions",
            },
        ),
    ]
