# Generated by Django 6.0.6 on 2026-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_seekerbillingsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekeraccount",
            name="avatar_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
