# Generated by Django 6.0.6 on 2026-07-02 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_candidate_deleted_at_jobseekeraccount_avatar_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("difficulty", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("examples", models.JSONField(default=list)),
                ("constraints", models.JSONField(default=list)),
                ("starter_code", models.JSONField(default=dict)),
                ("test_cases", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
            ],
            options={
                "db_table": "coding_problems",
            },
        ),
        migrations.CreateModel(
            name="MCQQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("question_text", models.TextField()),
                ("options", models.JSONField()),
                ("correct_option", models.CharField(max_length=1)),
                ("difficulty", models.CharField(default="medium", max_length=10)),
                ("tags", models.JSONField(default=list)),
            ],
            options={
                "db_table": "mcq_questions",
            },
        ),
        migrations.CreateModel(
            name="SessionRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Aptitude/MCQ Round"),
                            ("coding", "Coding Round"),
                            ("interview", "AI Interview Round"),
                        ],
                        max_length=20,
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("time_limit_minutes", models.IntegerField(default=30)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("result_announce_at", models.DateTimeField(blank=True, null=True)),
                ("mcq_question_count", models.IntegerField(default=30)),
                ("mcq_shuffle_seed", models.IntegerField(blank=True, null=True)),
                ("passing_score", models.IntegerField(default=50)),
                ("interview_questions", models.JSONField(default=list)),
                ("coding_problems", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "session",
                    models.ForeignKey(
                        db_column="session_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_rounds",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "db_table": "session_rounds",
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="ApplicantRoundAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", models.CharField(max_length=128, unique=True)),
                ("token_expires_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("mcq_questions_served", models.JSONField(default=list)),
                ("mcq_answers", models.JSONField(default=dict)),
                ("mcq_score", models.FloatField(blank=True, null=True)),
                ("coding_submissions", models.JSONField(default=list)),
                ("coding_score", models.FloatField(blank=True, null=True)),
                ("interview_transcript", models.JSONField(default=list)),
                ("interview_score", models.FloatField(blank=True, null=True)),
                ("interview_summary", models.TextField(blank=True)),
                (
                    "interview_recommendation",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "interview_hiring_likelihood",
                    models.CharField(blank=True, max_length=10),
                ),
                ("proctoring_flags", models.JSONField(default=list)),
                ("proctoring_score", models.FloatField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        db_column="candidate_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_attempts",
                        to="api.candidate",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        db_column="round_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="api.sessionround",
                    ),
                ),
            ],
            options={
                "db_table": "applicant_round_attempts",
                "unique_together": {("candidate", "round")},
            },
        ),
    ]
