# Generated by Django 6.0.6 on 2026-07-02 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_codingproblem_mcqquestion_sessionround_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeekerMockAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_type", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("score", models.FloatField(blank=True, null=True)),
                ("questions", models.JSONField(default=list)),
                ("answers", models.JSONField(default=dict)),
                ("feedback", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_attempts",
                        to="api.jobseekeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "seeker_mock_attempts",
            },
        ),
    ]
