# Generated by Django 6.0.6 on 2026-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_seekermockattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(db_index=True, default="new", max_length=50),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                db_index=True,
                default="applied",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(db_index=True, default="active", max_length=50),
        ),
    ]
