# Generated by Django 6.0.6 on 2026-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_candidate_status_alter_jobapplication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="developeraccount",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobseekeraccount",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobseekeraccount",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
