# Generated by Django 6.0.6 on 2026-07-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_company_email_verified_company_phone_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developeraccount",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
