# Generated by Django 6.0.6 on 2026-07-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_developeraccount_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="current_round_index",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="match_score",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="seekermockattempt",
            name="attempt_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="seekermockattempt",
            name="status",
            field=models.CharField(db_index=True, default="pending", max_length=20),
        ),
    ]
