# Generated by Django 6.0.6 on 2026-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_candidate_current_round_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
