# Generated by Django 6.0.7 on 2026-07-27 09:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_company_is_active_alter_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("job_seeker", "Job Seeker"),
                            ("developer", "Developer"),
                            ("recruiter", "Recruiter / Company"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("rating", models.IntegerField(default=5)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("role_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_column="company_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to="api.company",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        db_column="developer_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.developeraccount",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        blank=True,
                        db_column="recruiter_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_reviews",
                        to="api.company",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        blank=True,
                        db_column="seeker_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.jobseekeraccount",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
