# Generated by Django 6.0.7 on 2026-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudScanLog',
        ),
    ]
