# Generated by Django 6.0.7 on 2026-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_fraudscanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionround',
            name='round_type',
            field=models.CharField(choices=[('mcq', 'Aptitude/MCQ Round'), ('coding', 'Coding Round'), ('interview', 'AI Interview Round'), ('manual', 'Manual/HR Round')], max_length=20),
        ),
    ]
