from django.core.management.base import BaseCommand
from api.models import SkillTaxonomy

SKILL_SEED_DATA = [
    # Programming Languages
    ("Python", "Python", "Programming Languages", "Technical",
     ["py", "python3", "Python3"]),
    ("JavaScript", "JavaScript", "Programming Languages", "Technical",
     ["JS", "js", "javascript", "ECMAScript", "ES6"]),
    ("TypeScript", "TypeScript", "Programming Languages", "Technical",
     ["TS", "ts", "typescript"]),
    ("Java", "Java", "Programming Languages", "Technical",
     ["java", "Java EE", "Java SE"]),
    ("C++", "C++", "Programming Languages", "Technical",
     ["cpp", "c plus plus", "cplusplus"]),
    ("C#", "C#", "Programming Languages", "Technical",
     ["csharp", "c sharp", "dotnet c#", "CSharp"]),
    ("Go", "Go", "Programming Languages", "Technical",
     ["golang", "go lang", "Golang"]),
    ("Rust", "Rust", "Programming Languages", "Technical",
     ["rust lang", "rust language"]),
    ("Swift", "Swift", "Programming Languages", "Technical",
     ["swift lang", "apple swift"]),
    ("Kotlin", "Kotlin", "Programming Languages", "Technical",
     ["kotlin android"]),
    ("PHP", "PHP", "Programming Languages", "Technical",
     ["php7", "php8", "PHP7"]),
    ("Ruby", "Ruby", "Programming Languages", "Technical",
     ["ruby lang", "ruby programming"]),
    ("R", "R", "Programming Languages", "Technical",
     ["R language", "R programming", "rlang"]),
    ("Scala", "Scala", "Programming Languages", "Technical",
     ["scala lang"]),
    ("Dart", "Dart", "Programming Languages", "Technical",
     ["dart lang", "flutter dart"]),

    # Frontend
    ("React", "React", "Frontend", "Technical",
     ["React.js", "ReactJS", "react js", "reactjs"]),
    ("Vue.js", "Vue.js", "Frontend", "Technical",
     ["Vue", "VueJS", "vue js", "vue3", "Vue3"]),
    ("Angular", "Angular", "Frontend", "Technical",
     ["AngularJS", "angular js", "Angular2+", "angularjs"]),
    ("Next.js", "Next.js", "Frontend", "Technical",
     ["NextJS", "next js", "nextjs", "Next"]),
    ("Svelte", "Svelte", "Frontend", "Technical",
     ["svelte js", "sveltekit", "SvelteKit"]),
    ("Tailwind CSS", "Tailwind CSS", "Frontend", "Technical",
     ["Tailwind", "tailwindcss", "tailwind"]),
    ("HTML/CSS", "HTML/CSS", "Frontend", "Technical",
     ["HTML", "CSS", "HTML5", "CSS3", "html", "css"]),
    ("Redux", "Redux", "Frontend", "Technical",
     ["redux js", "react-redux", "Redux Toolkit"]),

    # Backend
    ("Node.js", "Node.js", "Backend", "Technical",
     ["NodeJS", "node js", "nodejs", "node"]),
    ("FastAPI", "FastAPI", "Backend", "Technical",
     ["fast api", "fastapi python"]),
    ("Django", "Django", "Backend", "Technical",
     ["django python", "django rest"]),
    ("Flask", "Flask", "Backend", "Technical",
     ["flask python", "flask api"]),
    ("Express.js", "Express.js", "Backend", "Technical",
     ["Express", "ExpressJS", "expressjs", "express js"]),
    ("Spring Boot", "Spring Boot", "Backend", "Technical",
     ["Spring", "SpringBoot", "spring framework"]),
    ("Laravel", "Laravel", "Backend", "Technical",
     ["laravel php"]),
    ("ASP.NET", "ASP.NET", "Backend", "Technical",
     ["asp.net core", "dotnet", "ASP.NET Core"]),
    ("GraphQL", "GraphQL", "Backend", "Technical",
     ["graph ql", "graphql api"]),
    ("REST API", "REST API", "Backend", "Technical",
     ["RESTful", "REST", "restful api", "rest apis"]),

    # Databases
    ("PostgreSQL", "PostgreSQL", "Databases", "Technical",
     ["Postgres", "psql", "postgresql", "postgres sql"]),
    ("MySQL", "MySQL", "Databases", "Technical",
     ["mysql", "My SQL"]),
    ("MongoDB", "MongoDB", "Databases", "Technical",
     ["Mongo", "mongodb", "mongo db", "mongoose"]),
    ("Redis", "Redis", "Databases", "Technical",
     ["redis cache", "redis db"]),
    ("Elasticsearch", "Elasticsearch", "Databases", "Technical",
     ["ES", "elastic", "elastic search", "opensearch"]),
    ("SQLite", "SQLite", "Databases", "Technical",
     ["sqlite3", "sqlite"]),
    ("Cassandra", "Cassandra", "Databases", "Technical",
     ["apache cassandra"]),
    ("DynamoDB", "DynamoDB", "Databases", "Technical",
     ["aws dynamodb", "dynamo db"]),
    ("Firebase", "Firebase", "Databases", "Technical",
     ["firebase db", "firestore", "google firebase"]),

    # Cloud & DevOps
    ("AWS", "AWS", "Cloud", "Technical",
     ["Amazon Web Services", "amazon aws", "AWS Cloud"]),
    ("GCP", "GCP", "Cloud", "Technical",
     ["Google Cloud", "Google Cloud Platform", "google gcp"]),
    ("Azure", "Azure", "Cloud", "Technical",
     ["Microsoft Azure", "azure cloud", "MS Azure"]),
    ("Docker", "Docker", "DevOps", "Technical",
     ["docker container", "dockerfile"]),
    ("Kubernetes", "Kubernetes", "DevOps", "Technical",
     ["K8s", "k8", "k8s", "kubernetes cluster"]),
    ("CI/CD", "CI/CD", "DevOps", "Technical",
     ["continuous integration", "continuous deployment", "CICD", "ci cd", "devops pipeline"]),
    ("Terraform", "Terraform", "DevOps", "Technical",
     ["terraform iac", "hashicorp terraform"]),
    ("Jenkins", "Jenkins", "DevOps", "Technical",
     ["jenkins ci", "jenkins pipeline"]),
    ("GitHub Actions", "GitHub Actions", "DevOps", "Technical",
     ["github actions", "GH Actions"]),
    ("Ansible", "Ansible", "DevOps", "Technical",
     ["ansible automation"]),
    ("Nginx", "Nginx", "DevOps", "Technical",
     ["nginx server", "nginx web server"]),

    # AI/ML
    ("TensorFlow", "TensorFlow", "AI/ML", "Technical",
     ["TF", "tensorflow", "tensor flow"]),
    ("PyTorch", "PyTorch", "AI/ML", "Technical",
     ["pytorch", "torch", "py torch"]),
    ("Scikit-learn", "Scikit-learn", "AI/ML", "Technical",
     ["sklearn", "scikit learn", "sklearn python"]),
    ("Pandas", "Pandas", "AI/ML", "Technical",
     ["pandas python", "pandas df", "pandas library"]),
    ("NumPy", "NumPy", "AI/ML", "Technical",
     ["numpy", "numpy python"]),
    ("Machine Learning", "Machine Learning", "AI/ML", "Technical",
     ["ML", "ml engineering", "machine-learning"]),
    ("Deep Learning", "Deep Learning", "AI/ML", "Technical",
     ["DL", "deep-learning", "neural networks", "NN"]),
    ("NLP", "NLP", "AI/ML", "Technical",
     ["Natural Language Processing", "natural language", "text mining", "NLP/NLU"]),
    ("Computer Vision", "Computer Vision", "AI/ML", "Technical",
     ["CV", "image recognition", "image processing", "object detection"]),
    ("LangChain", "LangChain", "AI/ML", "Technical",
     ["langchain", "lang chain"]),
    ("OpenAI API", "OpenAI API", "AI/ML", "Technical",
     ["GPT", "ChatGPT API", "openai", "GPT-4", "gpt api"]),
    ("Hugging Face", "Hugging Face", "AI/ML", "Technical",
     ["huggingface", "HF", "transformers library"]),

    # Data Engineering
    ("SQL", "SQL", "Data", "Technical",
     ["structured query language", "mysql sql", "sql query"]),
    ("Apache Spark", "Apache Spark", "Data", "Technical",
     ["Spark", "pyspark", "spark streaming"]),
    ("Apache Kafka", "Apache Kafka", "Data", "Technical",
     ["Kafka", "kafka streaming", "event streaming"]),
    ("Airflow", "Airflow", "Data", "Technical",
     ["apache airflow", "airflow dag"]),
    ("dbt", "dbt", "Data", "Technical",
     ["dbt analytics", "data build tool"]),
    ("Power BI", "Power BI", "Data", "Technical",
     ["PowerBI", "power bi desktop", "microsoft power bi"]),
    ("Tableau", "Tableau", "Data", "Technical",
     ["tableau desktop", "tableau server"]),
    ("Data Analysis", "Data Analysis", "Data", "Technical",
     ["data analytics", "analytics", "data analyst"]),
    ("Excel", "Excel", "Data", "Technical",
     ["MS Excel", "Microsoft Excel", "google sheets"]),

    # Mobile
    ("React Native", "React Native", "Mobile", "Technical",
     ["react-native", "RN", "react native mobile"]),
    ("Flutter", "Flutter", "Mobile", "Technical",
     ["flutter dart", "flutter mobile"]),
    ("Android", "Android", "Mobile", "Technical",
     ["android development", "android sdk", "android java"]),
    ("iOS", "iOS", "Mobile", "Technical",
     ["ios development", "iPhone development", "xcode", "ios swift"]),

    # Security
    ("Cybersecurity", "Cybersecurity", "Security", "Technical",
     ["cyber security", "information security", "infosec"]),
    ("Penetration Testing", "Penetration Testing", "Security", "Technical",
     ["pentesting", "pen testing", "ethical hacking"]),
    ("OWASP", "OWASP", "Security", "Technical",
     ["owasp security", "web security"]),

    # Soft Skills
    ("Leadership", "Leadership", "Soft Skills", "Non-Technical",
     ["team leadership", "people leadership"]),
    ("Communication", "Communication", "Soft Skills", "Non-Technical",
     ["verbal communication", "written communication"]),
    ("Problem Solving", "Problem Solving", "Soft Skills", "Non-Technical",
     ["analytical thinking", "analytical skills", "critical thinking"]),
    ("Team Management", "Team Management", "Soft Skills", "Non-Technical",
     ["people management", "team lead", "managing teams"]),
    ("Agile", "Agile", "Methodology", "Technical",
     ["agile methodology", "scrum", "kanban", "agile scrum"]),
    ("Project Management", "Project Management", "Methodology", "Technical",
     ["PMP", "project manager", "PM"]),
]

class Command(BaseCommand):
    help = "Seeds the skill taxonomy table with default values."

    def handle(self, *args, **options):
        count = SkillTaxonomy.objects.count()
        if count > 0:
            self.stdout.write(self.style.WARNING("Skill taxonomy is already seeded. Skipping."))
            return

        records = []
        for entry in SKILL_SEED_DATA:
            skill_name, canonical, category, parent, synonyms = entry
            records.append(SkillTaxonomy(
                skill_name=skill_name,
                canonical_name=canonical,
                category=category,
                parent_category=parent,
                synonyms=synonyms
            ))

        SkillTaxonomy.objects.bulk_create(records)
        self.stdout.write(self.style.SUCCESS(f"Successfully seeded {len(SKILL_SEED_DATA)} skills."))
